# Generated by Django 6.0.4 on 2026-04-23 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimentoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceite_termos', models.BooleanField(default=False)),
                ('finalidade', models.TextField(default='Armazenamento seguro e criptografado de credenciais de terceiros e gerenciamento de acesso.')),
                ('consentimento_ativo', models.BooleanField(default=True)),
                ('data_revogacao', models.DateTimeField(blank=True, null=True)),
                ('data_aceite', models.DateTimeField(auto_now_add=True)),
                ('versao_termo', models.CharField(default='1.0', max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
