# Generated by Django 6.0.4 on 2026-04-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='detalhes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='evento',
            field=models.CharField(choices=[('CADASTRO', 'Cadastro de Usuário'), ('LOGIN_SUCESSO', 'Sucesso no Login'), ('LOGIN_FALHA', 'Falha no Login'), ('BLOQUEIO_FORCA_BRUTA', 'Bloqueio por Força Bruta'), ('RECUPERACAO_SOLICITADA', 'Recuperação de Senha Iniciada'), ('RECUPERACAO_SUCESSO', 'Senha Redefinida')], max_length=50),
        ),
    ]
