# Generated by Django 6.0.4 on 2026-04-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_options_alter_auditlog_detalhes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='evento',
            field=models.CharField(choices=[('CADASTRO', 'Cadastro de Usuário'), ('LOGIN_SUCESSO', 'Sucesso no Login'), ('LOGIN_FALHA', 'Falha no Login'), ('LOGOUT', 'Logout do Sistema'), ('BLOQUEIO_FORCA_BRUTA', 'Bloqueio por Força Bruta'), ('RECUPERACAO_SOLICITADA', 'Recuperação de Senha Iniciada'), ('RECUPERACAO_SUCESSO', 'Senha Redefinida'), ('CRIACAO_SENHA_COFRE', 'Nova Senha no Cofre'), ('ALTERACAO_SENHA_COFRE', 'Senha Alterada no Cofre'), ('EXCLUSAO_SENHA_COFRE', 'Senha Excluída do Cofre')], max_length=50),
        ),
    ]
